wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1647391252
    t:
      1:
      - 5
      4: 3.9.6
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
