USE `family-relations`;

-- Family Table
DROP TABLE IF EXISTS Family;
CREATE TABLE Family(pid INT PRIMARY KEY REFERENCES Persons(Id), fid INT REFERENCES Persons(Id), mid INT REFERENCES Persons(Id));

-- Insert Info Into Family Table
-- Family 1
INSERT INTO FAMILY VALUES(1, 10, 11);
INSERT INTO FAMILY VALUES(2, 10, 11);
INSERT INTO FAMILY VALUES(3, 10, 11);
-- Family 2
INSERT INTO FAMILY VALUES(4, 12, 13);
INSERT INTO FAMILY VALUES(5, 12, 13);
INSERT INTO FAMILY VALUES(26, 12, 13);
-- Family 3
INSERT INTO FAMILY VALUES(6, 14, 15);
INSERT INTO FAMILY VALUES(7, 14, 15);
-- Grandparents
INSERT INTO FAMILY VALUES(10, 16, 17); -- father
INSERT INTO FAMILY VALUES(12, 16, 17); -- father's brother
INSERT INTO FAMILY VALUES(11, 18, 19); -- mother
INSERT INTO FAMILY VALUES(14, 18, 19); -- mother's brother
INSERT INTO FAMILY VALUES(13, 20, 21); -- aunt
INSERT INTO FAMILY VALUES(15, 22, 23); -- aunt
INSERT INTO FAMILY VALUES(24, 18, 19); -- mother's brother
INSERT INTO FAMILY VALUES(25, 18, 19); -- father's sister

-- View All In Family Table
SELECT * FROM FAMILY;