USE `family-relations`;

-- Persons Table
DROP TABLE IF EXISTS PERSONS;
CREATE TABLE PERSONS(id INT PRIMARY KEY, Name VARCHAR(64), Sex CHAR CHECK(Sex = 'M' OR Sex = 'F'));

-- Insert Info Into Persons Table
-- Children
INSERT INTO PERSONS VALUES (1, 'Azwad Shameem', 'M');
INSERT INTO PERSONS VALUES (2, 'Sister', 'F');
INSERT INTO PERSONS VALUES (3, 'Brother', 'M');
INSERT INTO PERSONS VALUES (4, 'Cousin 1', 'M');
INSERT INTO PERSONS VALUES (5, 'Cousin 2', 'F');
INSERT INTO PERSONS VALUES (6, 'Cousin 3', 'M');
INSERT INTO PERSONS VALUES (7, 'Cousin 4', 'F');
INSERT INTO PERSONS VALUES (8, 'Cousin 5', 'M');
INSERT INTO PERSONS VALUES (9, 'Cousin 6', 'F');
-- Parents
INSERT INTO PERSONS VALUES (10, 'Father', 'M');
INSERT INTO PERSONS VALUES (11, 'Mother', 'F');
INSERT INTO PERSONS VALUES (12, 'Uncle 1', 'M');
INSERT INTO PERSONS VALUES (13, 'Aunt 1', 'F');
INSERT INTO PERSONS VALUES (14, 'Uncle 2', 'M');
INSERT INTO PERSONS VALUES (15, 'Aunt 2', 'F');
-- Grand Parents
INSERT INTO PERSONS VALUES (16, 'Grandpa 1', 'M');
INSERT INTO PERSONS VALUES (17, 'Grandma 1', 'F');
INSERT INTO PERSONS VALUES (18, 'Grandpa 2', 'M');
INSERT INTO PERSONS VALUES (19, 'Grandma 2', 'F');
INSERT INTO PERSONS VALUES (20, 'Grandpa 3', 'M');
INSERT INTO PERSONS VALUES (21, 'Grandma 3', 'F');
INSERT INTO PERSONS VALUES (22, 'Grandpa 4', 'M');
INSERT INTO PERSONS VALUES (23, 'Grandma 4', 'F');


-- Adults (Non-Parents)
INSERT INTO PERSONS VALUES (24, 'Uncle 3', 'M');
INSERT INTO PERSONS VALUES (25, 'Aunt 4', 'F');
INSERT INTO PERSONS VALUES (26, 'Cousin 10', 'M');

-- View All In Persons Table
SELECT * FROM PERSONS;