USE `family-relations`;

-- SPOUSES Table
DROP TABLE IF EXISTS SPOUSES;
CREATE TABLE SPOUSES(hid INT REFERENCES Persons(Id), wid INT REFERENCES Persons(Id), PRIMARY KEY (hid, wid));

-- Insert Info Into Husband-Wife Table
INSERT INTO SPOUSES VALUES(10, 11);
INSERT INTO SPOUSES VALUES(12, 13);
INSERT INTO SPOUSES VALUES(14, 15);
INSERT INTO SPOUSES VALUES(16, 17);
INSERT INTO SPOUSES VALUES(18, 19);
INSERT INTO SPOUSES VALUES(20, 21);
INSERT INTO SPOUSES VALUES(22, 23);

-- View All In SPOUSES Table
SELECT * FROM SPOUSES;